# Generated by Django 4.1.5 on 2023-01-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebetCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Пост')),
                ('stoimost', models.CharField(max_length=255, verbose_name='Стоимость обслуживания')),
                ('dostavka', models.CharField(max_length=255, verbose_name='доставка')),
                ('cashback', models.FloatField(verbose_name='кэшбэк')),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='post',
            name='categoryPost',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='descriptionSeo',
            field=models.TextField(null=True, verbose_name='Description Seo'),
        ),
        migrations.AddField(
            model_name='post',
            name='titleSeo',
            field=models.CharField(max_length=255, null=True, verbose_name='Титле сео'),
        ),
    ]
