# Generated by Django 4.1.5 on 2023-01-06 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_debetcard_alter_post_options_post_categorypost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryPost',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.debetcard'),
        ),
    ]
