# Generated by Django 4.1.5 on 2023-01-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_categorypost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoryPost',
        ),
        migrations.AddField(
            model_name='post',
            name='categoryPost',
            field=models.ManyToManyField(null=True, to='core.debetcard'),
        ),
    ]
