# Generated by Django 4.1.5 on 2023-01-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_categorypost_post_categorypost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bank', verbose_name='банк'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='categoryPost',
        ),
        migrations.AddField(
            model_name='post',
            name='categoryPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.debetcard', verbose_name='Debetcard'),
        ),
    ]
