# Generated by Django 4.1.5 on 2023-01-08 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ratingstar_remove_post_rating_post_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='фильмы'),
        ),
    ]
