# Generated by Django 4.1.5 on 2023-01-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_rating_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Debetcard'),
        ),
        migrations.DeleteModel(
            name='DebetCard',
        ),
    ]
