# Generated by Django 4.1.5 on 2023-02-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_post_categorypost_delete_debetcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descriptionSeo',
            field=models.TextField(null=True, verbose_name='Dblog_post_detailescription Seo'),
        ),
    ]
