# Generated by Django 4.1.5 on 2023-03-05 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.TextField(null=True, verbose_name='Ссылка на партнерку'),
        ),
        migrations.AlterField(
            model_name='post',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bank', verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoryPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='descriptionSeo',
            field=models.TextField(null=True, verbose_name='Description Seo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='otziv',
            field=models.TextField(verbose_name='Отзывы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titleSeo',
            field=models.CharField(max_length=255, null=True, verbose_name='Title сео'),
        ),
    ]
