# Generated by Django 4.1.5 on 2023-03-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_post_link_alter_post_bank_alter_post_categorypost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(null=True, upload_to='', verbose_name='Иконка'),
        ),
    ]
