# Generated by Django 4.1.5 on 2023-03-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_categoryclass_post_podcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryclass',
            options={'verbose_name': 'Под Категория', 'verbose_name_plural': 'Под Категории'},
        ),
        migrations.AlterField(
            model_name='categoryclass',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Под категория'),
        ),
    ]
