# Generated by Django 4.1.5 on 2023-03-05 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_categoryclass_options_alter_categoryclass_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='categoryclass',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categoryPost',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='podcategory',
            new_name='classes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='categoryclass',
            name='categoryPost',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='categoryclass',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoryclass',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Под категория '),
        ),
    ]
