# Generated by Django 4.1.5 on 2023-03-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_url_bank_slug_rename_url_category_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='slug',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='categoryclass',
            old_name='slug',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='categoryPost',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='classes',
            new_name='podcategory',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='categoryclass',
            name='parent',
        ),
        migrations.AddField(
            model_name='categoryclass',
            name='categoryPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория'),
        ),
    ]
