# Generated by Django 4.1.5 on 2023-03-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_bank_url_remove_category_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Основная категория')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('icon', models.ImageField(null=True, upload_to='', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Основная Категория',
                'verbose_name_plural': 'Основная Категории',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='maincategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate', to='core.maincategory', verbose_name='Основная'),
        ),
    ]
