# Generated by Django 4.1.5 on 2023-03-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_post_maincategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='descriptions',
            field=models.CharField(max_length=160, null=True, verbose_name='Seo Description'),
        ),
        migrations.AddField(
            model_name='bank',
            name='title',
            field=models.CharField(max_length=80, null=True, verbose_name='Seo Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='descriptions',
            field=models.CharField(max_length=160, null=True, verbose_name='Seo Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=80, null=True, verbose_name='Seo Title'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='descriptions',
            field=models.CharField(max_length=160, null=True, verbose_name='Seo Description'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='title',
            field=models.CharField(max_length=80, null=True, verbose_name='Seo Title'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='descriptions',
            field=models.CharField(max_length=160, null=True, verbose_name='Seo Description'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=80, null=True, verbose_name='Seo Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='descriptionSeo',
            field=models.CharField(max_length=160, null=True, verbose_name='Description Seo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titleSeo',
            field=models.CharField(max_length=80, null=True, verbose_name='Title сео'),
        ),
    ]
