# Generated by Django 3.2.18 on 2023-03-25 18:47

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_bank_descriptions_bank_title_category_descriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bank',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='bank',
            name='mini_icons',
            field=models.ImageField(null=True, upload_to='', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='bank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='url_off_site',
            field=models.CharField(max_length=120, null=True, verbose_name='Офф сайт'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='mini_icons',
            field=models.ImageField(null=True, upload_to='', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
