# Generated by Django 3.2.18 on 2023-05-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_bank_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subcategories',
            field=models.ManyToManyField(null=True, related_name='posts', to='core.SubCategory'),
        ),
    ]
