# Generated by Django 3.2.18 on 2023-05-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_post_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subcategories',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='core.SubCategory'),
        ),
    ]
